# This workflow will build and publish an APK to the latest release
# See https://github.com/docker/build-push-action

name: Publish APK

on:
  release:
    types: [published]

jobs:
  publish_to_release:
    name: Publish APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Set version variable
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build APK with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleRelease
        
    - name: Upload APK
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: TaskerHealthConnect-${{ steps.vars.outputs.tag }}.apk
